# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

jobs:
- job: docker_build
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    imageName: 'qt:5.12.12-ubuntu18.04-$(build.buildId)'

  steps:
  - script: docker build -f 18.04/5.12.12/Dockerfile -t $(imageName) .
    displayName: Build

  timeoutInMinutes: 360
